export const tarotCards = [
  // === 大阿尔卡纳 (0-21) ===
  { id: 0, name: "愚者", meaning: "新的开始、冒险、纯真、自发性", revMeaning: "鲁莽、疏忽、愚蠢、犹豫不决", image: new URL("./imgs/愚者.jpg", import.meta.url).href },
  { id: 1, name: "魔术师", meaning: "创造力、意志力、显化、能力", revMeaning: "幻觉、操纵、怀才不遇、计划延误", image: new URL("./imgs/魔术师.jpg", import.meta.url).href },
  { id: 2, name: "女祭司", meaning: "直觉、神秘、潜意识、内在智慧", revMeaning: "肤浅、隐藏的动机、忽视直觉、秘密泄露", image: new URL("./imgs/女祭司.jpg", import.meta.url).href },
  { id: 3, name: "皇后", meaning: "丰饶、创造力、母性、自然、感官", revMeaning: "创造力受阻、依赖、缺乏安全感、贫瘠", image: new URL("./imgs/皇后.jpg", import.meta.url).href },
  { id: 4, name: "皇帝", meaning: "权威、稳定、保护、结构、逻辑", revMeaning: "专横、缺乏控制、严苛、效率低下", image: new URL("./imgs/皇帝.jpg", import.meta.url).href },
  { id: 5, name: "教皇", meaning: "传统、信仰、指引、体制、社会规范", revMeaning: "叛逆、挑战权威、打破常规、思想僵化", image: new URL("./imgs/教皇.jpg", import.meta.url).href },
  { id: 6, name: "恋人", meaning: "关系、价值观的一致、选择、爱", revMeaning: "失调、不平衡、逃避责任、错误的决策", image: new URL("./imgs/恋人.jpg", import.meta.url).href },
  { id: 7, name: "战车", meaning: "意志力、胜利、决心、自律、控制", revMeaning: "失去方向、侵略性、软弱、受挫", image: new URL("./imgs/战车.jpg", import.meta.url).href },
  { id: 8, name: "力量", meaning: "勇气、耐心、内在力量、温柔的控制", revMeaning: "软弱、自我怀疑、缺乏耐心、恐惧", image: new URL("./imgs/力量.jpg", import.meta.url).href },
  { id: 9, name: "隐士", meaning: "独处、内省、指引、寻求真相", revMeaning: "孤独、隔离、偏执、过于隐遁", image: new URL("./imgs/隐士.jpg", import.meta.url).href },
  { id: 10, name: "命运之轮", meaning: "机会、周期、转折点、好运、宿命", revMeaning: "厄运、阻碍、外部阻力、坏循环", image: new URL("./imgs/命运之轮.jpg", import.meta.url).href },
  { id: 11, name: "正义", meaning: "公平、真相、因果、法律、平衡", revMeaning: "不公平、偏见、不承认责任、法律纠纷", image: new URL("./imgs/正义.jpg", import.meta.url).href },
  { id: 12, name: "倒吊人", meaning: "暂停、牺牲、新视角、放下、等待", revMeaning: "拖延、无谓的牺牲、逃避、原地踏步", image: new URL("./imgs/倒吊人.jpg", import.meta.url).href },
  { id: 13, name: "死神", meaning: "结束、转化、过渡、深刻的变化", revMeaning: "抗拒改变、停滞不前、恐惧、腐朽", image: new URL("./imgs/死神.jpg", import.meta.url).href },
  { id: 14, name: "节制", meaning: "平衡、中庸、耐心、整合、和谐", revMeaning: "失衡、极端、缺乏目标、浪费", image: new URL("./imgs/节制.jpg", import.meta.url).href },
  { id: 15, name: "恶魔", meaning: "束缚、成瘾、物质欲望、阴影面", revMeaning: "解脱、觉醒、对抗诱惑、打破束缚", image: new URL("./imgs/恶魔.jpg", import.meta.url).href },
  { id: 16, name: "塔", meaning: "突变、混乱、灾难、真相揭露", revMeaning: "恐惧灾难、延迟崩塌、幸免于难", image: new URL("./imgs/塔.jpg", import.meta.url).href },
  { id: 17, name: "星星", meaning: "希望、灵感、疗愈、宁静、信心", revMeaning: "绝望、悲观、缺乏灵感、信心动摇", image: new URL("./imgs/星星.jpg", import.meta.url).href },
  { id: 18, name: "月亮", meaning: "幻觉、恐惧、不安、潜意识、梦境", revMeaning: "真相浮现、恐惧消除、误解澄清", image: new URL("./imgs/月亮.jpg", import.meta.url).href },
  { id: 19, name: "太阳", meaning: "喜悦、成功、活力、自信、积极", revMeaning: "短暂的消沉、过度自大、延迟的成功", image: new URL("./imgs/太阳.jpg", import.meta.url).href },
  { id: 20, name: "审判", meaning: "觉醒、重生、评判、使命、清算", revMeaning: "自我怀疑、拒绝召唤、拖延决定", image: new URL("./imgs/审判.jpg", import.meta.url).href },
  { id: 21, name: "世界", meaning: "圆满、集成、成就、旅行、圆满结束", revMeaning: "未完成、停滞、缺乏展望、结局不顺", image: new URL("./imgs/世界.jpg", import.meta.url).href },

  // === 权杖组 (22-35) - 火元素：行动、能量 ===
  { id: 22, name: "权杖王牌", meaning: "新的机遇、灵感、行动的开始", revMeaning: "缺乏动力、计划夭折、创意受阻", image: new URL("./imgs/权杖王牌.jpg", import.meta.url).href },
  { id: 23, name: "权杖二", meaning: "远见、规划、决策、初步成功", revMeaning: "目光短浅、犹豫不决、规划失误", image: new URL("./imgs/权杖二.jpg", import.meta.url).href },
  { id: 24, name: "权杖三", meaning: "扩张、展望、商业贸易、等待成果", revMeaning: "沟通受阻、延误、视野狭窄", image: new URL("./imgs/权杖三.jpg", import.meta.url).href },
  { id: 25, name: "权杖四", meaning: "庆祝、和谐、家庭、稳固、安宁", revMeaning: "内部不和、不稳定的局面、庆典取消", image: new URL("./imgs/权杖四.jpg", import.meta.url).href },
  { id: 26, name: "权杖五", meaning: "竞争、冲突、争论、分歧", revMeaning: "达成妥协、逃避冲突、内战结束", image: new URL("./imgs/权杖五.jpg", import.meta.url).href },
  { id: 27, name: "权杖六", meaning: "胜利、荣誉、公开认可、进展", revMeaning: "落后、失去名誉、短暂的胜利", image: new URL("./imgs/权杖六.jpg", import.meta.url).href },
  { id: 28, name: "权杖七", meaning: "防守、坚持、挑战、面对压力", revMeaning: "妥协、放弃、不堪重负", image: new URL("./imgs/权杖七.jpg", import.meta.url).href },
  { id: 29, name: "权杖八", meaning: "迅速、消息、旅行、快速行动", revMeaning: "延迟、混乱、速度过慢、阻碍", image: new URL("./imgs/权杖八.jpg", import.meta.url).href },
  { id: 30, name: "权杖九", meaning: "防御、坚持、最后一搏、警惕", revMeaning: "防御崩溃、精疲力竭、防备过当", image: new URL("./imgs/权杖九.jpg", import.meta.url).href },
  { id: 31, name: "权杖十", meaning: "责任、压力、负担、辛劳", revMeaning: "卸下负担、崩溃、逃避责任", image: new URL("./imgs/权杖十.jpg", import.meta.url).href },
  { id: 32, name: "权杖侍从", meaning: "好奇心、消息、热情、新的探索", revMeaning: "流言蜚语、缺乏耐心、坏消息", image: new URL("./imgs/权杖侍从.jpg", import.meta.url).href },
  { id: 33, name: "权杖骑士", meaning: "冒险、冲劲、大胆、行动力", revMeaning: "鲁莽、暴躁、半途而废", image: new URL("./imgs/权杖骑士.jpg", import.meta.url).href },
  { id: 34, name: "权杖王后", meaning: "自信、开朗、独立、社交能力", revMeaning: "情绪化、嫉妒、控制欲、自私", image: new URL("./imgs/权杖王后.jpg", import.meta.url).href },
  { id: 35, name: "权杖国王", meaning: "领导力、远见、企业家精神、权威", revMeaning: "独裁、冲动、无情、自大", image: new URL("./imgs/权杖国王.jpg", import.meta.url).href },

  // === 圣杯组 (36-49) - 水元素：情感、关系 ===
  { id: 36, name: "圣杯王牌", meaning: "新的感情、慈悲、爱、灵性觉醒", revMeaning: "情感受阻、空虚、犹豫不决、失恋", image: new URL("./imgs/圣杯王牌.jpg", import.meta.url).href },
  { id: 37, name: "圣杯二", meaning: "伙伴关系、吸引力、契合、统一", revMeaning: "不和谐、分手、关系失衡", image: new URL("./imgs/圣杯二.jpg", import.meta.url).href },
  { id: 38, name: "圣杯三", meaning: "庆典、社交、友谊、团队协作", revMeaning: "过度纵乐、三人行纠纷、孤立", image: new URL("./imgs/圣杯三.jpg", import.meta.url).href },
  { id: 39, name: "圣杯四", meaning: "冥想、厌倦、重新评估、冷漠", revMeaning: "新的机遇、觉醒、摆脱停滞", image: new URL("./imgs/圣杯四.jpg", import.meta.url).href },
  { id: 40, name: "圣杯五", meaning: "悲伤、失落、沉溺过去、失望", revMeaning: "接受现实、释怀、走出阴影", image: new URL("./imgs/圣杯五.jpg", import.meta.url).href },
  { id: 41, name: "圣杯六", meaning: "怀旧、童心、纯真、旧情", revMeaning: "沉溺过去、不切实际、未来的挑战", image: new URL("./imgs/圣杯六.jpg", import.meta.url).href },
  { id: 42, name: "圣杯七", meaning: "幻想、多种选择、白日梦、诱惑", revMeaning: "认清现实、做出决定、清晰的目标", image: new URL("./imgs/圣杯七.jpg", import.meta.url).href },
  { id: 43, name: "圣杯八", meaning: "追寻、离去、放弃、寻找真相", revMeaning: "逃避、犹豫、无处可去、害怕改变", image: new URL("./imgs/圣杯八.jpg", import.meta.url).href },
  { id: 44, name: "圣杯九", meaning: "满足、愿望达成、享乐、感官满足", revMeaning: "贪婪、不满足、表面快乐、过度消费", image: new URL("./imgs/圣杯九.jpg", import.meta.url).href },
  { id: 45, name: "圣杯十", meaning: "幸福、美满家庭、和谐、情感圆满", revMeaning: "家庭冲突、关系破裂、价值观不合", image: new URL("./imgs/圣杯十.jpg", import.meta.url).href },
  { id: 46, name: "圣杯侍从", meaning: "艺术气息、敏感、好消息、感性", revMeaning: "情绪化、逃避现实、幼稚、欺骗", image: new URL("./imgs/圣杯侍从.jpg", import.meta.url).href },
  { id: 47, name: "圣杯骑士", meaning: "浪漫、诚挚、邀请、追随梦想", revMeaning: "花心、情绪化、不切实际的承诺", image: new URL("./imgs/圣杯骑士.jpg", import.meta.url).href },
  { id: 48, name: "圣杯王后", meaning: "直觉、慈悲、温柔、母性、感性", revMeaning: "不可靠、过度敏感、情绪勒索", image: new URL("./imgs/圣杯王后.jpg", import.meta.url).href },
  { id: 49, name: "圣杯国王", meaning: "情感稳定、睿智、冷静、外交手腕", revMeaning: "冷酷、操纵情感、易怒、反复无常", image: new URL("./imgs/圣杯国王.jpg", import.meta.url).href },

  // === 宝剑组 (50-63) - 风元素：思想、逻辑、冲突 ===
  { id: 50, name: "宝剑王牌", meaning: "精神突破、清晰的见解、正义、权力", revMeaning: "混乱、滥用权力、误解、思想受阻", image: new URL("./imgs/宝剑王牌.jpg", import.meta.url).href },
  { id: 51, name: "宝剑二", meaning: "僵局、逃避现实、艰难的选择", revMeaning: "犹豫不决、信息过载、真相大白", image: new URL("./imgs/宝剑二.jpg", import.meta.url).href },
  { id: 52, name: "宝剑三", meaning: "伤心、痛苦、分离、悲伤", revMeaning: "康复、释怀、压抑痛苦、疗愈中", image: new URL("./imgs/宝剑三.jpg", import.meta.url).href },
  { id: 53, name: "宝剑四", meaning: "休息、冥想、康复、静止", revMeaning: "精疲力竭、焦虑、重新投入行动", image: new URL("./imgs/宝剑四.jpg", import.meta.url).href },
  { id: 54, name: "宝剑五", meaning: "损人利己的胜利、争斗、背叛", revMeaning: "冲突结束、寻求和解、两败俱伤", image: new URL("./imgs/宝剑五.jpg", import.meta.url).href },
  { id: 55, name: "宝剑六", meaning: "过渡、旅行、渡过难关、平息", revMeaning: "陷入困境、延迟、无法摆脱过去", image: new URL("./imgs/宝剑六.jpg", import.meta.url).href },
  { id: 56, name: "宝剑七", meaning: "欺骗、潜逃、策略、孤军奋战", revMeaning: "坦白、被识破、难以实施计划", image: new URL("./imgs/宝剑七.jpg", import.meta.url).href },
  { id: 57, name: "宝剑八", meaning: "束缚、受限、危机、自我怀疑", revMeaning: "解脱、自由、新视角、面对恐惧", image: new URL("./imgs/宝剑八.jpg", import.meta.url).href },
  { id: 58, name: "宝剑九", meaning: "焦虑、失眠、噩梦、极度压力", revMeaning: "希望曙光、接受帮助、走出阴影", image: new URL("./imgs/宝剑九.jpg", import.meta.url).href },
  { id: 59, name: "宝剑十", meaning: "惨败、跌落谷底、背叛、终结", revMeaning: "触底反弹、痛苦结束、重生", image: new URL("./imgs/宝剑十.jpg", import.meta.url).href },
  { id: 60, name: "宝剑侍从", meaning: "警惕、好奇、头脑风暴、逻辑", revMeaning: "轻率、讽刺、虚假消息、防御心重", image: new URL("./imgs/宝剑侍从.jpg", import.meta.url).href },
  { id: 61, name: "宝剑骑士", meaning: "果断、迅速、直言不讳、进攻", revMeaning: "鲁莽、由于愤怒而冲动、分散精力", image: new URL("./imgs/宝剑骑士.jpg", import.meta.url).href },
  { id: 62, name: "宝剑王后", meaning: "独立、客观、公正、敏锐", revMeaning: "冷酷、刻薄、偏见、苦恼", image: new URL("./imgs/宝剑王后.jpg", import.meta.url).href },
  { id: 63, name: "宝剑国王", meaning: "智力、纪律、真理、权威", revMeaning: "独裁、滥用权力、冷酷、偏执", image: new URL("./imgs/宝剑国王.jpg", import.meta.url).href },

  // === 星币组 (64-77) - 土元素：物质、身体、金钱 ===
  { id: 64, name: "星币王牌", meaning: "新财务机会、繁荣、显化、物质开端", revMeaning: "错失机会、财务损失、贪婪", image: new URL("./imgs/星币王牌.jpg", import.meta.url).href },
  { id: 65, name: "星币二", meaning: "平衡、管理、适应性、多任务处理", revMeaning: "失衡、混乱、过度透支、决策困难", image: new URL("./imgs/星币二.jpg", import.meta.url).href },
  { id: 66, name: "星币三", meaning: "团队协作、学习、技能提升、认可", revMeaning: "缺乏协作、技术拙劣、工作不顺", image: new URL("./imgs/星币三.jpg", import.meta.url).href },
  { id: 67, name: "星币四", meaning: "稳定、安全感、节俭、占有欲", revMeaning: "铺张浪费、开放、放手、物质危机", image: new URL("./imgs/星币四.jpg", import.meta.url).href },
  { id: 68, name: "星币五", meaning: "物质困难、贫困、孤立、健康问题", revMeaning: "财务改善、恢复、找到援手", image: new URL("./imgs/星币五.jpg", import.meta.url).href },
  { id: 69, name: "星币六", meaning: "慷慨、慈善、平衡的给予与获得", revMeaning: "不平等、自私、滥用金钱、负债", image: new URL("./imgs/星币六.jpg", import.meta.url).href },
  { id: 70, name: "星币七", meaning: "收获前的等待、耐心、长远回报", revMeaning: "缺乏规划、收效甚微、不耐烦", image: new URL("./imgs/星币七.jpg", import.meta.url).href },
  { id: 71, name: "星币八", meaning: "工匠精神、勤奋、学习、专注", revMeaning: "平庸、缺乏专注、偷懒、工作枯燥", image: new URL("./imgs/星币八.jpg", import.meta.url).href },
  { id: 72, name: "星币九", meaning: "自给自足、丰盛、奢侈、独立生活", revMeaning: "虚荣、财务受困、过度依赖、孤独", image: new URL("./imgs/星币九.jpg", import.meta.url).href },
  { id: 73, name: "星币十", meaning: "家庭财富、遗产、长久的稳定", revMeaning: "家庭纷争、破产、短视、传统破裂", image: new URL("./imgs/星币十.jpg", import.meta.url).href },
  { id: 74, name: "星币侍从", meaning: "雄心壮志、务实、新项目、勤学", revMeaning: "缺乏目标、眼高手低、财务坏消息", image: new URL("./imgs/星币侍从.jpg", import.meta.url).href },
  { id: 75, name: "星币骑士", meaning: "可靠、耐心、保守、辛勤工作", revMeaning: "保守停滞、单调、懒惰、死板", image: new URL("./imgs/星币骑士.jpg", import.meta.url).href },
  { id: 76, name: "星币王后", meaning: "务实、滋养、财务安全、繁荣", revMeaning: "自私、控制欲、金钱焦虑、虚伪", image: new URL("./imgs/星币王后.jpg", import.meta.url).href },
  { id: 77, name: "星币国王", meaning: "物质成功、纪律、丰饶、商业领袖", revMeaning: "贪婪、腐败、物质主义、顽固", image: new URL("./imgs/星币国王.jpg", import.meta.url).href },
];
